workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m1
    scripts:
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
